In [3]:
# This notebook demonstrates how to download and process air quality monitoring data from various networks.
import download
# Define the networks to get metadata for
networks = ["aurn", "saqn", "aqe", "waqn", "ni"]

# Dictionary to store metadata for each network
metadata_dict = {}

# Loop through each network, download metadata, and store it in the dictionary
for network in networks:
    print(f"Fetching metadata for {network} network...")
    metadata = download.monitoring_station_meta_data(network)
    metadata_dict[network] = metadata
    print(f"Metadata for {network} network:")
    display(metadata)

# Define stations and their respective data parameters
stations_data = {
    "saqn": ["ABD1", 2015, "NO"],
    "aqe": ["YK9", 2015, "PM10"],
    "waqn": ["ANG5", 2010, "PM10"],
    "ni": ["DCSMOB01", 2019, "PM2.5"],
    "aurn": ["ABD", 2015, "O3"]
}

# Loop through each station data entry, download the data, and display the first few rows
for network, station_data in stations_data.items():
    station, year, pollutant = station_data
    print(f"Fetching data for station {station} in {year} from {network} network...")
    data = download.import_monitoring_station_data(station, pollutant, year, network)
    print(f"Data for {station} in {year} from {network} network:")
    display(data.head())

Fetching metadata for aurn network...

'http://uk-air.defra.gov.uk/openair/R_data/AURN_metadata.RData'

Download completed successfully.
Metadata for aurn network:

,site_id,site_name,location_type,latitude,longitude,parameter,Parameter_name,start_date,end_date,ratified_to,zone,agglomeration,local_authority
0,ABD,Aberdeen,Urban Background,57.157360,-2.094278,O3,Ozone,2003-08-01,2021-09-20,2021-09-20,North East Scotland,NA_character_,Aberdeen City
1,ABD,Aberdeen,Urban Background,57.157360,-2.094278,NO,Nitric oxide,1999-09-18,2021-09-20,2021-09-20,North East Scotland,NA_character_,Aberdeen City
2,ABD,Aberdeen,Urban Background,57.157360,-2.094278,NO2,Nitrogen dioxide,1999-09-18,2021-09-20,2021-09-20,North East Scotland,NA_character_,Aberdeen City
3,ABD,Aberdeen,Urban Background,57.157360,-2.094278,NOXasNO2,Nitrogen oxides as nitrogen dioxide,1999-09-18,2021-09-20,2021-09-20,North East Scotland,NA_character_,Aberdeen City
4,ABD,Aberdeen,Urban Background,57.157360,-2.094278,SO2,Sulphur dioxide,2001-01-01,2007-09-30,2007-09-30,North East Scotland,NA_character_,Aberdeen City
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2816,YK11,York Fishergate,Urban Traffic,53.951889,-1.075861,NV2.5,Non-volatile PM2.5 (Hourly measured),2011-08-31,2018-10-10,2018-10-10,Yorkshire & Humberside,NA_character_,York
2817,YK11,York Fishergate,Urban Traffic,53.951889,-1.075861,V2.5,Volatile PM2.5 (Hourly measured),2011-08-31,2018-10-10,2018-10-10,Yorkshire & Humberside,NA_character_,York
2818,YK11,York Fishergate,Urban Traffic,53.951889,-1.075861,wd,Modelled Wind Direction,2010-08-01,ongoing,Never,Yorkshire & Humberside,NA_character_,York
2819,YK11,York Fishergate,Urban Traffic,53.951889,-1.075861,ws,Modelled Wind Speed,2010-08-01,ongoing,Never,Yorkshire & Humberside,NA_character_,York
2820,YK11,York Fishergate,Urban Traffic,53.951889,-1.075861,temp,Modelled Temperature,2010-08-01,ongoing,Never,Yorkshire & Humberside,NA_character_,York

Fetching metadata for saqn network...

'https://www.scottishairquality.scot/openair/R_data/SCOT_metadata.RData'

Download completed successfully.
Metadata for saqn network:

,site_id,site_name,location_type,latitude,longitude,parameter,Parameter_name,start_date,end_date,ratified_to,zone,agglomeration,local_authority
0,ABD1,Aberdeen Anderson Dr,Urban Traffic,57.128567,-2.125447,NO,Nitric oxide,2005-01-01,ongoing,2023-12-31,North East Scotland,NA_character_,Aberdeen City
1,ABD1,Aberdeen Anderson Dr,Urban Traffic,57.128567,-2.125447,NO2,Nitrogen dioxide,2005-01-01,ongoing,2023-12-31,North East Scotland,NA_character_,Aberdeen City
2,ABD1,Aberdeen Anderson Dr,Urban Traffic,57.128567,-2.125447,NOXasNO2,Nitrogen oxides as nitrogen dioxide,2005-01-01,ongoing,2023-12-31,North East Scotland,NA_character_,Aberdeen City
3,ABD1,Aberdeen Anderson Dr,Urban Traffic,57.128567,-2.125447,PM10,PM10 particulate matter (Hourly measured),2005-01-01,ongoing,2024-03-31,North East Scotland,NA_character_,Aberdeen City
4,ABD1,Aberdeen Anderson Dr,Urban Traffic,57.128567,-2.125447,PM2.5,PM2.5 particulate matter (Hourly measured),2021-07-20,ongoing,2024-03-31,North East Scotland,NA_character_,Aberdeen City
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,WHIT,West Lothian Whitburn,Urban Background,55.866092,-3.684857,NV10,Non-volatile PM10 (Hourly measured),2010-02-10,2012-04-03,2012-04-03,Central Scotland,NA_character_,West Lothian
1336,WHIT,West Lothian Whitburn,Urban Background,55.866092,-3.684857,V10,Volatile PM10 (Hourly measured),2010-02-10,2012-04-03,2012-04-03,Central Scotland,NA_character_,West Lothian
1337,WHIT,West Lothian Whitburn,Urban Background,55.866092,-3.684857,wd,Modelled Wind Direction,2010-08-01,2012-04-03,Never,Central Scotland,NA_character_,West Lothian
1338,WHIT,West Lothian Whitburn,Urban Background,55.866092,-3.684857,ws,Modelled Wind Speed,2010-08-01,2012-04-03,Never,Central Scotland,NA_character_,West Lothian
1339,WHIT,West Lothian Whitburn,Urban Background,55.866092,-3.684857,temp,Modelled Temperature,2010-08-01,2012-04-03,Never,Central Scotland,NA_character_,West Lothian

Fetching metadata for aqe network...

'https://airqualityengland.co.uk/assets/openair/R_data/AQE_metadata.RData'

Download completed successfully.
Metadata for aqe network:

,site_id,site_name,location_type,latitude,longitude,parameter,Parameter_name,start_date,end_date,ratified_to,zone,agglomeration,local_authority
0,AIY008,"1st Charlton Scouts, Shepperton (sensor)",Urban Background,51.406200,-0.443486,NO2,Nitrogen dioxide,2023-11-14,ongoing,2023-12-31,South East,NA_character_,Spelthorne
1,AIY008,"1st Charlton Scouts, Shepperton (sensor)",Urban Background,51.406200,-0.443486,PM10,PM10 particulate matter (Hourly measured),2023-11-14,ongoing,2023-12-31,South East,NA_character_,Spelthorne
2,AIY008,"1st Charlton Scouts, Shepperton (sensor)",Urban Background,51.406200,-0.443486,PM2.5,PM2.5 particulate matter (Hourly measured),2023-11-14,ongoing,2023-12-31,South East,NA_character_,Spelthorne
3,AIY007,"1st Sunbury Scouts, Sunbury (sensor)",Urban Background,51.406900,-0.417956,NO2,Nitrogen dioxide,2023-11-14,ongoing,2023-12-22,Greater London,Greater London Urban Area,Spelthorne
4,AIY007,"1st Sunbury Scouts, Sunbury (sensor)",Urban Background,51.406900,-0.417956,PM10,PM10 particulate matter (Hourly measured),2023-11-14,ongoing,2023-12-22,Greater London,Greater London Urban Area,Spelthorne
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533,YK9,York Lawrence Street,Urban Traffic,53.954663,-1.068241,NOXasNO2,Nitrogen oxides as nitrogen dioxide,2015-01-01,ongoing,2023-12-31,Yorkshire & Humberside,NA_character_,York
1534,YK15,York Nunnery Lane,Urban Traffic,53.953411,-1.086275,NO,Nitric oxide,2015-01-01,ongoing,2023-12-31,Yorkshire & Humberside,NA_character_,York
1535,YK15,York Nunnery Lane,Urban Traffic,53.953411,-1.086275,NO2,Nitrogen dioxide,2015-01-01,ongoing,2023-12-31,Yorkshire & Humberside,NA_character_,York
1536,YK15,York Nunnery Lane,Urban Traffic,53.953411,-1.086275,NOXasNO2,Nitrogen oxides as nitrogen dioxide,2015-01-01,ongoing,2023-12-31,Yorkshire & Humberside,NA_character_,York
1537,YK018,York Plantation Drive,Urban Traffic,53.966432,-1.126061,PM10,PM10 particulate matter (Hourly measured),2016-01-01,ongoing,2023-12-31,Yorkshire & Humberside,NA_character_,York

Fetching metadata for waqn network...

'https://airquality.gov.wales/sites/default/files/openair/R_data/WAQ_metadata.RData'

Download completed successfully.
Metadata for waqn network:

,site_id,site_name,location_type,latitude,longitude,parameter,Parameter_name,start_date,end_date,ratified_to,zone,agglomeration,local_authority
0,ANG5,Anglesey Brynteg,Rural Industrial,53.307155,-4.274216,PM10,Particulates < 10um (hourly measured),2007-08-01,2022-12-31,2022-12-31,North Wales,NA_character_,Isle of Anglesey
1,ANG5,Anglesey Brynteg,Rural Industrial,53.307155,-4.274216,PM2.5,Particulates < 2.5um (hourly measured),2007-08-01,2022-12-31,2022-12-31,North Wales,NA_character_,Isle of Anglesey
2,ANG5,Anglesey Brynteg,Rural Industrial,53.307155,-4.274216,PM1,Particulates < 1um (hourly measured),2007-08-01,2022-12-31,2022-12-31,North Wales,NA_character_,Isle of Anglesey
3,ANG5,Anglesey Brynteg,Rural Industrial,53.307155,-4.274216,TSP,Total Suspended Particulate,2007-08-01,2022-12-31,2022-12-31,North Wales,NA_character_,Isle of Anglesey
4,ANG5,Anglesey Brynteg,Rural Industrial,53.307155,-4.274216,wd,Modelled Wind Direction,2010-08-01,2022-12-31,Never,North Wales,NA_character_,Isle of Anglesey
...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,WRX4,Wrexham Isycoed,Urban Industrial,53.048475,-2.900658,SO2,Sulphur dioxide,2006-01-01,2015-12-31,2015-12-31,North Wales,NA_character_,Wrexham
618,WRX4,Wrexham Isycoed,Urban Industrial,53.048475,-2.900658,GR10,PM10 Particulate matter (daily measured),2006-01-01,2015-12-31,2015-12-31,North Wales,NA_character_,Wrexham
619,WRX4,Wrexham Isycoed,Urban Industrial,53.048475,-2.900658,wd,Modelled Wind Direction,2010-08-01,2015-12-31,Never,North Wales,NA_character_,Wrexham
620,WRX4,Wrexham Isycoed,Urban Industrial,53.048475,-2.900658,ws,Modelled Wind Speed,2010-08-01,2015-12-31,Never,North Wales,NA_character_,Wrexham
621,WRX4,Wrexham Isycoed,Urban Industrial,53.048475,-2.900658,temp,Modelled Temperature,2010-08-01,2015-12-31,Never,North Wales,NA_character_,Wrexham

Fetching metadata for ni network...

'https://www.airqualityni.co.uk/openair/R_data/NI_metadata.RData'

Download completed successfully.
Metadata for ni network:

,site_id,site_name,location_type,latitude,longitude,parameter,Parameter_name,start_date,end_date,ratified_to,zone,agglomeration,local_authority
0,ANT1,Antrim Greystone Estate,Urban Background,54.709900,-6.188552,SO2,Sulphur dioxide,2004-11-25,2010-06-18,2010-06-18,Northern Ireland,NA_character_,Antrim and Newtownabbey
1,ARDS,Ards Glen community centre,Urban Background,54.599072,-5.699291,SO2,Sulphur dioxide,2003-03-01,2006-04-10,2006-03-15,Northern Ireland,NA_character_,Ards and North Down
2,ARDS,Ards Glen community centre,Urban Background,54.599072,-5.699291,PM10,PM10 particulate matter (Hourly measured),2003-03-01,2006-04-10,2006-03-15,Northern Ireland,NA_character_,Ards and North Down
3,ARD2,Ards Leisure Centre,Urban Background,54.597019,-5.703319,SO2,Sulphur dioxide,2006-04-11,2010-04-06,2010-04-06,Northern Ireland,NA_character_,Ards and North Down
4,ARD2,Ards Leisure Centre,Urban Background,54.597019,-5.703319,PM10,PM10 particulate matter (Hourly measured),2006-04-11,2011-10-25,2011-10-25,Northern Ireland,NA_character_,Ards and North Down
...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,DCSMOB01,Strathfoyle Bawnmore Place,Suburban Background,55.034322,-7.264644,PM10,PM10 particulate matter (Hourly measured),2018-08-01,ongoing,2023-12-31,Northern Ireland,NA_character_,Derry and Strabane
313,DCSMOB01,Strathfoyle Bawnmore Place,Suburban Background,55.034322,-7.264644,PM2.5,PM2.5 particulate matter (Hourly measured),2022-02-25,ongoing,2023-12-31,Northern Ireland,NA_character_,Derry and Strabane
314,DCSMOB01,Strathfoyle Bawnmore Place,Suburban Background,55.034322,-7.264644,wd,Modelled Wind Direction,2018-08-01,ongoing,Never,Northern Ireland,NA_character_,Derry and Strabane
315,DCSMOB01,Strathfoyle Bawnmore Place,Suburban Background,55.034322,-7.264644,ws,Modelled Wind Speed,2018-08-01,ongoing,Never,Northern Ireland,NA_character_,Derry and Strabane
316,DCSMOB01,Strathfoyle Bawnmore Place,Suburban Background,55.034322,-7.264644,temp,Modelled Temperature,2018-08-01,ongoing,Never,Northern Ireland,NA_character_,Derry and Strabane

Fetching data for station ABD1 in 2015 from saqn network...
https://www.scottishairquality.scot/openair/R_data/ABD1_2015.RData
Download completed successfully for ABD1 in 2015.
All files downloaded successfully.
Data for ABD1 in 2015 from saqn network:

,date,NO,NO2,NOXasNO2,PM10,wd,ws,temp,site,code
0,1.420070e+09,1.2473,3.8250,5.7375,12.932,229.9,8.2,7.1,Aberdeen Anderson Dr,1
1,1.420074e+09,NaN,NaN,NaN,5.112,230.0,7.8,6.6,Aberdeen Anderson Dr,1
2,1.420078e+09,1.2473,3.8250,5.7375,6.136,234.6,9.1,6.7,Aberdeen Anderson Dr,1
3,1.420081e+09,1.2473,5.7375,7.6500,5.372,236.4,9.5,6.9,Aberdeen Anderson Dr,1
4,1.420085e+09,0.0000,3.8250,3.8250,8.645,226.1,8.9,7.0,Aberdeen Anderson Dr,1

Fetching data for station YK9 in 2015 from aqe network...
https://airqualityengland.co.uk/assets/openair/R_data/YK9_2015.RData
Download completed successfully for YK9 in 2015.
All files downloaded successfully.
Data for YK9 in 2015 from aqe network:

           date      NO      NO2  NOXasNO2                  site  code
0  1.420070e+09  6.2365  30.6000   40.1625  York Lawrence Street     1
1  1.420074e+09  9.9784  24.8625   40.1625  York Lawrence Street     1
2  1.420078e+09  6.2365  24.8625   34.4250  York Lawrence Street     1
3  1.420081e+09  3.7419  17.2125   22.9500  York Lawrence Street     1
4  1.420085e+09  2.4946  11.4750   15.3000  York Lawrence Street     1

Fetching data for station ANG5 in 2010 from waqn network...
https://airquality.gov.wales/sites/default/files/openair/R_data/ANG5_2010.RData
Download completed successfully for ANG5 in 2010.
All files downloaded successfully.
Data for ANG5 in 2010 from waqn network:

           date  PM10  PM2.5  PM1   TSP  wd  ws  temp              site  code
0  1.262304e+09  12.0    5.0  2.0  11.0 NaN NaN   NaN  Anglesey Brynteg     1
1  1.262308e+09   9.0    3.0  1.0   8.0 NaN NaN   NaN  Anglesey Brynteg     1
2  1.262311e+09   8.0    3.0  0.0   7.0 NaN NaN   NaN  Anglesey Brynteg     1
3  1.262315e+09   7.0    2.0  0.0   6.0 NaN NaN   NaN  Anglesey Brynteg     1
4  1.262318e+09   8.0    2.0  0.0   6.0 NaN NaN   NaN  Anglesey Brynteg     1

Fetching data for station DCSMOB01 in 2019 from ni network...
https://www.airqualityni.co.uk/openair/R_data/DCSMOB01_2019.RData
Download completed successfully for DCSMOB01 in 2019.
All files downloaded successfully.
Data for DCSMOB01 in 2019 from ni network:

           date   PM10                        site  code
0  1.554077e+09   9.76  Strathfoyle Bawnmore Place     1
1  1.554080e+09   8.30  Strathfoyle Bawnmore Place     1
2  1.554084e+09  12.21  Strathfoyle Bawnmore Place     1
3  1.554088e+09  13.39  Strathfoyle Bawnmore Place     1
4  1.554091e+09  15.89  Strathfoyle Bawnmore Place     1

Fetching data for station ABD in 2015 from aurn network...
https://uk-air.defra.gov.uk/openair/R_data/ABD_2015.RData
Download completed successfully for ABD in 2015.
All files downloaded successfully.
Data for ABD in 2015 from aurn network:

,date,O3,NO,NO2,NOXasNO2,PM10,NV10,V10,PM2.5,NV2.5,V2.5,wd,ws,temp,AT10,AT2.5,AP2.5,site,code
0,1.420070e+09,62.79803,1.46766,9.19275,11.44313,12.6,12.2,0.4,11.4,9.0,2.4,229.9,8.2,7.1,10.1,13.1,999435.0,Aberdeen,1
1,1.420074e+09,67.45466,0.85939,9.21379,10.53150,5.3,3.4,1.9,11.4,8.0,3.4,230.0,7.8,6.6,9.7,12.6,999600.0,Aberdeen,1
2,1.420078e+09,70.94714,0.64454,6.99593,7.98421,4.2,0.0,4.2,5.8,0.3,5.5,234.6,9.1,6.7,9.0,11.9,999017.0,Aberdeen,1
3,1.420081e+09,74.78886,0.83226,3.97561,5.25173,-2.3,0.6,-2.9,2.0,1.4,0.6,236.4,9.5,6.9,9.4,12.4,999050.0,Aberdeen,1
4,1.420085e+09,75.13811,0.96635,3.72698,5.20869,3.3,1.7,1.6,1.3,0.8,0.5,226.1,8.9,7.0,9.6,12.6,999000.0,Aberdeen,1